### ISSUE TITLE
Parameterize CLI improvements

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/htmd#934]
### 1
Some users might need to enable some modules before running psi4 for example.
Currently the CLI does not allow any modifications to the run.sh

### 2
Add some documentation on how to add config files for the queues such as SLURM

`config_slurm.yml`
```yaml
psi4:
  partition: normalCPU
  ncpu: 4
  ngpu: 0
  memory: 3000

acemd:
  partition: normalGPU
  ncpu: 1
  ngpu: 1
  memory: 4000
```

`export HTMD_CONFIG=/my/path/config.py`
`config.py`
```python
from htmd.config import config
config(slurm='/home/sdoerr/Work/jobqueues/jobqueues/config_slurm.yml')
```
